SL-872
silence-laboratories/sl-crypto pull request #8
Opened 2024-04-04 09:04 UTC by eclipse7

2024-04-22 13:03 UTC, left-arm requested changes

2024-04-22 13:03 UTC, left-arm commented on crates/sl-oblivious/Cargo.toml
The PR changes API, we have to update version to "0.2.0"

2024-04-22 13:03 UTC, left-arm commented on crates/sl-oblivious/src/endemic_ot.rs
could we use define `type CompressedPoint = [u8; 33];` and use it?

2024-04-23 09:14 UTC, left-arm approved these changes
LGTM

2024-06-04 09:56 UTC, leontiad approved these changes
got it

2024-06-04 10:02 UTC, merged